environments:
  - name: ADLN
    gio_cmd: 
      - "gio_plugin -jsonfile dynamic_param.json -requestby karn.jye.lau@intel.com -auto_clone true -sourcetestcycle 53144 -newtestcycle PLUTO_ADLN_Bronze_Staging-RT -testcyclegroup 1349 -result_type html -suiteid 12877,12878,12879 -add_date true -nowait -bomlist -uuid 2c4d9625-6337-458d-b50d-1878e7054180 -nowait"
      - "gio_plugin -jsonfile dynamic_param.json -requestby karn.jye.lau@intel.com -auto_clone true -sourcetestcycle 53143 -newtestcycle PLUTO_ADLN_Bronze_Staging-LTS -testcyclegroup 1349 -result_type html -suiteid 12880,12881,12882 -add_date true -nowait -bomlist -uuid 2c4d9625-6337-458d-b50d-1878e7054180 -nowait"

  - name: ADLPS
    gio_cmd: 
      - "gio_plugin -jsonfile dynamic_param.json -requestby karn.jye.lau@intel.com -auto_clone true -newtestcycle PLUTO_ADLPS_Bronze_Staging-LTS -result_type html -nowait -bomlist -add_date true -uuid 2c4d9625-6337-458d-b50d-1878e7054180 -sourcetestcycle 53242 -testcyclegroup 1301 -suiteid 12965,12966,12967,12968,12969,12970,12971 -suiterunid 84971,84970,84966,84967,84968,84969,84973,84976,84977,84978,84981,84985,84986,96169,96170,96171,96182,96184,96185,96186,96303,84987,84988,84989,84990,96055,96056,84994,84995,95597,84997,84998,84999,85001,85002,95600 -nowait"

  - name: ICX
    gio_cmd: 
      - "gio_plugin -jsonfile dynamic_param.json -requestby hemanthX.dp@intel.com -auto_clone true -sourcetestcycle 108094 -newtestcycle PLUTO_EDLD-LCC_Bronze_Staging-LTS -testcyclegroup 1965 -result_type html -suiteid 13386 -add_date true -nowait -bomlist -uuid 3db66fc1-4d52-4ca4-817c-c4c1d61fdb02 -nowait"
      - "gio_plugin -jsonfile dynamic_param.json -requestby hemanthX.dp@intel.com -auto_clone true -sourcetestcycle 108095 -newtestcycle PLUTO_EDLD-LCC_Bronze_Staging-RT -testcyclegroup 1965 -result_type html -suiteid 13387 -add_date true -nowait -bomlist -uuid 3db66fc1-4d52-4ca4-817c-c4c1d61fdb02 -nowait"
      - "gio_plugin -jsonfile dynamic_param.json -requestby hemanthX.dp@intel.com -auto_clone true -sourcetestcycle 108094 -newtestcycle PLUTO_EDLD-HCC_Bronze_Staging-LTS -testcyclegroup 1965 -result_type html -suiteid 13388 -add_date true -nowait -bomlist -uuid 3db66fc1-4d52-4ca4-817c-c4c1d61fdb02 -nowait"
      - "gio_plugin -jsonfile dynamic_param.json -requestby hemanthX.dp@intel.com -auto_clone true -sourcetestcycle 108095 -newtestcycle PLUTO_EDLD-HCC_Bronze_Staging-RT -testcyclegroup 1965 -result_type html -suiteid 13544 -add_date true -nowait -bomlist -uuid 3db66fc1-4d52-4ca4-817c-c4c1d61fdb02 -nowait"
 
  - name: ADL
    gio_cmd: 
      - "gio_plugin -jsonfile dynamic_param.json -requestby kalavenix.joseph@intel.com -auto_clone true -sourcetestcycle 59973 -newtestcycle PLUTO_ADLS_INT.SAT_Staging-LTS -testcyclegroup 1576 -result_type html -suiteid 10040 -add_date true -nowait -bomlist -uuid 2460c0ca-0d05-49d6-8d15-66960f9e64db -nowait"
      - "gio_plugin -jsonfile dynamic_param.json -requestby kalavenix.joseph@intel.com -auto_clone true -sourcetestcycle 59974 -newtestcycle PLUTO_ADLS_INT.SAT_Staging-RT -testcyclegroup 1576 -result_type html -suiteid 10041 -add_date true -nowait -bomlist -uuid 2460c0ca-0d05-49d6-8d15-66960f9e64db -nowait" 
      - "gio_plugin -jsonfile dynamic_param.json -requestby kalavenix.joseph@intel.com -auto_clone true -sourcetestcycle 59970 -newtestcycle PLUTO_ADLP_INT.SAT_Staging-LTS -testcyclegroup 1577 -result_type html -suiteid 10329 -add_date true -nowait -bomlist -uuid 2460c0ca-0d05-49d6-8d15-66960f9e64db -nowait"

  - name: RPLS
    gio_cmd: 
      - "gio_plugin -jsonfile dynamic_param.json -requestby ganeash.shanmuganathan@intel.com -sourcetestcycle 34596 -testcyclegroup 1244 -suiteid 13221 -suiterunid 86678,86679,86667,86668,86669,86670,86671,86680,86672,86673,86674,86675,86676,86677,86682 -newtestcycle PLUTO_RPL-S_Bronze_Staging-LTS -uuid 098c406a-cfc0-4c42-93e5-49f8a8a068e0 -auto_clone true -add_date true -nowait"
      - "gio_plugin -jsonfile dynamic_param.json -requestby ganeash.shanmuganathan@intel.com -sourcetestcycle 58605 -testcyclegroup 1244 -suiteid 13222 -suiterunid 89825,86698,86686,86687,86699,86690,86688,86689,86691,86692,86693,86694,86695,86696,86697,86701 -newtestcycle PLUTO_RPL-S_Bronze_Staging-RT -uuid 098c406a-cfc0-4c42-93e5-49f8a8a068e0 -auto_clone true -add_date true -nowait"

kernel_mapping:
    Primary_Kernel_Config:
        LTS-STAGING:
            LTS_kernel: intel-iot-staging-6.6
            RT_kernel: intel-iot-staging-rt-6.6
            Kernel_version_number: 6.6
        LTS:
            LTS_kernel: iot-lts-6.6
            RT_kernel: iot-lts-rt-6.6-kernel
            Kernel_version_number: 6.6
    Secondary_Kernel_Config:
        LTS-STAGING:
            LTS_kernel: intel-iot-staging-6.1
            RT_kernel: intel-iot-staging-rt-6.1
            Kernel_version_number: 6.1
        LTS:
            LTS_kernel: iot-lts-6.1
            RT_kernel: iot-lts-rt-6.1-kernel
            Kernel_version_number: 6.1
